export const GET_COUNTRIES = "GET_COUNTRIES",
            GET_ACTIVITIES = "GET_ACTIVITIES",
       GET_NAME_COUNTRIES  = "GET_NAME_COUNTRIES",
           POST_ACTIVITIES = "POST_ACTIVITIES",
      FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES",
       FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT",
      FILTER_BY_POPULATION = "FILTER_BY_POPULATION",
                      SORT = "SORT";